title: Xin Wu
# tagline: Here is personal website of Hanlin Cai. Powered by Jekyll, based on the Minimal Mistakes theme.
# description: Two roads diverged in woods, I took the one less traveled by.
#Comment out url when working locally to resolve base urls correctly
url: https://xinwu74.github.io

# Owner/author information
owner:
  name: Xin WU
  avatar: wuxin.jpg
  bio: üéÑ Keep the passion for all research. Craftsmanship spirit, engineering mindset.  üéÑ ‰øùÊåÅÁÉ≠ÊÉÖ„ÄÇÂ∑•Âå†Á≤æÁ•ûÔºåÂ∑•Á®ãÊÄùÁª¥„ÄÇ
  # email: wu1351658806@163.com
  cv: https://xinwu74.github.io/file/CV-XInWU_ZH.pdf
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # twitter: lancecai2002
  github: wuliwuxin
  # linkedin: hanlincai
  # scholar: https://scholar.google.com/citations?user=8igSoWgAAAAJ
  scholar: https://scholar.google.com/citations?user=1O2QQB8AAAAJ
  bilibili: 404809876
  # researchgate: https://www.researchgate.net/profile/Hanlin-Cai
  researchgate: https://www.researchgate.net/profile/Xin-Wu-111
  zhihu: https://www.zhihu.com/people/wu-xin-24-36-6
  # facebook: caihanlin2002
  # instagram: lancecai2002
  # lastfm:
  # tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/
  - title: Projects
    url: /projects/
  - title: Awards
    url: /awards/
  # - title: Teams
  #   url: /teams/
  # - title: Notes
    # url: /notes/
  - title: Blogs
    url: /blogs/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Beijing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: lancecai

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]

# Latest update in 2023/12/10 by Xin WU.